### ISSUE TITLE
Is the HPE vendor fully functional?

### ISSUE THREAD

**Issue by jtudelag** [redhat-partner-solutions/crucible#10]
### Bug description

Hey,

We are about to use crucible to provision HPE servers. 

Looking at the code it seems there are some places where "HPE" is missing, like in the validate_invetory role: https://github.com/redhat-partner-solutions/crucible/blob/main/roles/validate_inventory/defaults/main.yml#L13

Or in this other role: https://github.com/redhat-partner-solutions/crucible/blob/main/roles/boot_disk/tasks/main.yml

So, we are wondering if Crucible is fully functional when working with HPE servers, or it requires additional work.

Thanks!

### OpenShift version

4.7

### Assisted Installer version

v1.0.24.2

### Required statements

- [X] I have removed all sensitive details from the attached logs and inventory files.
- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by Rajeev244** [comment]
hi team,

I am deploying ocp cluster 4.9 on vm's hosted on KVM.after the host discovery and validation step ,when the cluster installation starts it throws an error about the validation.On checking the assisted installer logs it shows the below errror
"build)\",\"argv\":[\"smartctl\",\"--xall\",\"--json=c\",\"/dev/vda\"],\"messages\":[{\"string\":\"/dev/vda: Unable to detect device type\",\"severity\":\"error\"}],"
even though the vda disk is created on the vm's.

Appreciate your response if anyone faced this .

**Comment by nocturnalastro** [comment]
@Rajeev244 Can you make a new issue, please.
