### ISSUE TITLE
deploy_dns runs validations trying to connect to names not created yet

### ISSUE THREAD

**Issue by broskos** [redhat-partner-solutions/crucible#122]
### Bug description

I'm adding extra_dns records to create DNS records for the BMCs.  Before creating these records, the deploy_dns playbook runs validations which check to ensure BMC addresses are reachable.  The DNS records are not created at this point, so the validation fails, resulting in the playbook not creating the DNS records needed.

Why am I creating DNS records for BMCs?  

I'm behind a proxy.  NO_PROXY does a great job of not using the proxy for subdomains like 'mgmt.ocloud.lab', this will skip the proxy for any addresses in that domain like 'super1-idrac.mgmt.ocloud.lab'  and so on.  However NO_PROXY does NOT understand CIDR notation in many cases, so I can't simply add a value for the BMC network like 192.168.51.0/24 - this does not work.

### OpenShift version

4.8

### Assisted Installer version

v1.0.24.2

### Required statements

- [X] I have removed all sensitive details from the attached logs and inventory files.
- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by nocturnalastro** [comment]
Addressed in PR #134
