### ISSUE TITLE
Ansible community.general version 5 up breaks compatibility with ansible 2.9

### ISSUE THREAD

**Issue by dsedgmen** [redhat-partner-solutions/crucible#152]
### Bug description

This a simple fix, we can either set the version in the requirements.yaml or change 'community.general.nmcli' to 'nmcli
https://github.com/ansible-collections/community.general/pull/4548

### OpenShift version

other (provide in the description)

### Assisted Installer version

other (provide in the description)

### Relevant log output

```shell
ERROR! couldn't resolve module/action 'community.general.nmcli'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ocp/crucible/roles/destroy_vms/tasks/destroy_networks.yml': line 15, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Delete existing bridges (if any)
  ^ here
```

### Required statements

- [X] I have removed all sensitive details from the attached logs and inventory files.
- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by nocturnalastro** [comment]
PR to fix this #143
