### ISSUE TITLE
"deploy_assisted_installer_onprem.yml" playbook is getting failed on task:Wait for up to 60 minutes for the assisted installer to come online due to no assisted-installer pod is available

### ISSUE THREAD

**Issue by poojagupta1418** [redhat-partner-solutions/crucible#212]
### Bug description

We are deploying OCP4.12.0  on "on-premises" environment with env details as (3 master and 3 workers node as virtual machine)
While running "deploy_assisted_installer_onprem.yml" we observe it is getting failed to task""Wait for up to 60 minutes for the assisted installer to come online"  (screenshot is attached)
after understanding the code, it is observed that playbook removing assisted-installer pod but it is still looking for its connection.

Below is the details of pod/container which are created after executing the playbook:
[root~]# podman ps
CONTAINER ID  IMAGE                                                                                                                                              COMMAND               CREATED        STATUS             PORTS                                                                   NAMES
207abdc77461  docker.io/library/registry:latest                                                                                                                  /etc/docker/regis...  4 months ago   Up 2 hours ago     0.0.0.0:5000->5000/tcp                                                  Mirror-Registry
719b39ac593c  registry.access.redhat.com/ubi8/pause:latest                                                                                                       infinity              4 hours ago    Up 4 hours ago     0.0.0.0:80->8080/tcp                                                    0e8df1078fc0-infra
4a8b2e27d9c3  registry.centos.org/centos/httpd-24-centos7:latest                                                                                                 /usr/bin/run-http...  4 hours ago    Up 4 hours ago     0.0.0.0:80->8080/tcp                                                    http_store
37a2d7585a8c  registry.access.redhat.com/ubi8/pause:latest                                                                                                       infinity              7 minutes ago  Up 7 minutes ago   0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp, 0.0.0.0:8888->8888/tcp  51c000ca4760-infra
bc5326b7ab54  registry.nfvi.localdomain:5000/edge-infrastructure/assisted-installer-ui@sha256:xxx   /deploy/start.sh      7 minutes ago  Up 7 minutes ago   0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp, 0.0.0.0:8888->8888/tcp  assisted-installer-ui
f716ea9b7bb3  registry.nfvi.localdomain:5000/edge-infrastructure/assisted-image-service@sha256:xxx  /assisted-image-s...  7 minutes ago  Up 7 minutes ago   0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp, 0.0.0.0:8888->8888/tcp  assisted-installer-image-service
b2f8950efe19  registry.nfvi.localdomain:5000/edge-infrastructure/assisted-service@sha256:xxx        /assisted-service     7 minutes ago  Up 10 seconds ago  0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp, 0.0.0.0:8888->8888/tcp  assisted-installer-service

![error](https://user-images.githubusercontent.com/45872943/215137076-a6e665ea-2937-4414-88a6-669e23a283f6.png)
![error](https://user-images.githubusercontent.com/45872943/215137076-a6e665ea-2937-4414-88a6-669e23a283f6.png)

### OpenShift version

other (provide in the description)

### Assisted Installer version

v2.1.1

### Required statements

- [X] I have removed all sensitive details from the attached logs and inventory files.
- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by poojagupta1418** [comment]
Team, 
Kindly support on the mentioned issue.
Will be appreciate your prompt response towards the solution.

Thanks!!

**Comment by nocturnalastro** [comment]
Can you check on the assisted installer host that port is open? Also check your firewall.

**Comment by nocturnalastro** [comment]
@poojagupta1418 Any updates on this?

**Comment by nocturnalastro** [comment]
Not able to recreate and no updates for almost a year so going to assume it has been fixed.
If you are still having this issues feel free to reopen.
