### ISSUE TITLE
mirror registry problem

### ISSUE THREAD

**Issue by wufeng2x** [redhat-partner-solutions/crucible#253]
### Bug description

TASK [populate_mirror_registry : Build pruned OLM index] ********************************************************************************************************
fatal: [registry_host]: FAILED! => changed=true 
  cmd:
  - /usr/local/bin/opm
  - index
  - prune
  - --from-index
  - registry.redhat.io/redhat/redhat-operator-index:v4.12
  - --packages
  - advanced-cluster-management,cluster-logging,kubevirt-hyperconverged,local-storage-operator,ocs-operator,performance-addon-operator,ptp-operator,sriov-network-operator
  - --tag
  - registry.example.lab:5000/olm-index/redhat-operator-index:v4.12
  delta: '0:00:37.338661'
  end: '2023-07-18 10:31:20.759498'
  msg: non-zero return code
  rc: 1
  start: '2023-07-18 10:30:43.420837'
  stderr: |-
    time="2023-07-18T10:30:43+08:00" level=warning msg="\x1b[1;33mDEPRECATION NOTICE:\nSqlite-based catalogs and their related subcommands are deprecated. Support for\nthem will be removed in a future release. Please migrate your catalog workflows\nto the new file-based catalog format.\x1b[0m"
    time="2023-07-18T10:30:43+08:00" level=info msg="pruning the index" packages="[advanced-cluster-management cluster-logging kubevirt-hyperconverged local-storage-operator ocs-operator performance-addon-operator ptp-operator sriov-network-operator]"
    time="2023-07-18T10:30:43+08:00" level=info msg="Pulling previous image registry.redhat.io/redhat/redhat-operator-index:v4.12 to get metadata" packages="[advanced-cluster-management cluster-logging kubevirt-hyperconverged local-storage-operator ocs-operator performance-addon-operator ptp-operator sriov-network-operator]"
    time="2023-07-18T10:30:43+08:00" level=info msg="running /bin/podman pull registry.redhat.io/redhat/redhat-operator-index:v4.12" packages="[advanced-cluster-management cluster-logging kubevirt-hyperconverged local-storage-operator ocs-operator performance-addon-operator ptp-operator sriov-network-operator]"
    time="2023-07-18T10:31:11+08:00" level=info msg="running /bin/podman pull registry.redhat.io/redhat/redhat-operator-index:v4.12" packages="[advanced-cluster-management cluster-logging kubevirt-hyperconverged local-storage-operator ocs-operator performance-addon-operator ptp-operator sriov-network-operator]"
    time="2023-07-18T10:31:20+08:00" level=info msg="Getting label data from previous image" packages="[advanced-cluster-management cluster-logging kubevirt-hyperconverged local-storage-operator ocs-operator performance-addon-operator ptp-operator sriov-network-operator]"
    time="2023-07-18T10:31:20+08:00" level=info msg="running podman inspect" packages="[advanced-cluster-management cluster-logging kubevirt-hyperconverged local-storage-operator ocs-operator performance-addon-operator ptp-operator sriov-network-operator]"
    Error: `opm index prune` only supports sqlite-based catalogs. See https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/793 for instructions on pruning a plaintext files backed catalog.
    Usage:
      opm index prune [flags]
  
    Flags:
      -i, --binary-image opm        container image for on-image opm command
      -c, --container-tool string   tool to interact with container images (save, build, etc.). One of: [docker, podman] (default "podman")
      -f, --from-index string       index to prune
          --generate                if enabled, just creates the dockerfile and saves it to local disk
      -h, --help                    help for prune
      -d, --out-dockerfile string   if generating the dockerfile, this flag is used to (optionally) specify a dockerfile name
      -p, --packages strings        comma separated list of packages to keep
          --permissive              allow registry load errors
      -t, --tag string              custom tag for container image being built
  
    Global Flags:
          --skip-tls-verify   skip TLS certificate verification for container image registries while pulling bundles
          --use-http          use plain HTTP for container image registries while pulling bundles
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

### OpenShift version

other (provide in the description)

### Assisted Installer version

other (provide in the description)

### Required statements

- [X] I have removed all sensitive details from the attached logs and inventory files.
- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by nocturnalastro** [comment]
@wufeng2x this should be fixed now can you verify?

**Comment by nocturnalastro** [comment]
@wufeng2x I'm going to assume this is fixed now. Feel free to reopen it if you have this issue in the future.
