### ISSUE TITLE
Add the ability to deploy OCP using PXE boot

### ISSUE THREAD

**Issue by natifridman** [redhat-partner-solutions/crucible#92]
### Feature description

There are some vendors who don't fully support Redfish API. This prevents us from deploying OCP using Crucible in our lab.
Adding to Crucible the ability to deploy OCP clusters using PXE boot can help us to deploy OCP labs faster.

### Required statements

- [X] I acknowledge that Red Hat does not provide commercial support for the content of this repository.
- [X] I acknowledge that any assistance is offered purely on a best-effort basis, as resource permits.

**Comment by snecklifter** [comment]
@natifridman just curious which vendors? If this is old kit then it seems like a large code base to maintain going forward when we seem to have all the major bases covered already. Especially as the number of nodes that don't support redfish continues to decrease and a lot of security departments don't particularly like enabling PXE/DHCP/TFTP.

**Comment by natifridman** [comment]
> @natifridman just curious which vendors? If this is old kit then it seems like a large code base to maintain going forward when we seem to have all the major bases covered already. Especially as the number of nodes that don't support redfish continues to decrease and a lot of security departments don't particularly like enabling PXE/DHCP/TFTP.

Intel specifically, but it can also be a solution for others like Supermicro that requires a license for Redfish.
